# Generated by Django 3.0.7 on 2020-08-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200803_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date',
        ),
    ]
