# Generated by Django 3.0.7 on 2020-08-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_users_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateField(verbose_name='Create Date'),
        ),
    ]
