# Generated by Django 3.0.7 on 2020-08-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200805_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date',
        ),
    ]
