# Generated by Django 3.0.7 on 2020-08-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, verbose_name='Username')),
                ('password', models.CharField(max_length=10, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Sign',
                'verbose_name_plural': 'Signs',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, verbose_name='Name')),
                ('Username', models.CharField(max_length=10, verbose_name='Username')),
                ('Phone', models.IntegerField(verbose_name='Phone')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Password', models.CharField(max_length=10, verbose_name='Password')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2, verbose_name='Gener')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
