# Generated by Django 3.0.7 on 2020-08-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersRegister', '0002_auto_20200806_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2, verbose_name='Gener'),
        ),
    ]
