# Generated by Django 3.0.7 on 2020-08-07 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersRegister', '0003_auto_20200806_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
    ]
